### ISSUE TITLE
API Gateway service의 Eureka 등록으로 인한 Routing 설정 변경

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#13]
- AS-IS
```yml
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9001/
          predicates:
            - Path=/user/**
```
> 실제 서버의 연결정보(ip, hostname, port)를 기반으로 forwarding 대상 micro-service routing 정보 설정

- TO-BE
```yml
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
```
> Eureka Server에 등록된 Instance의 spring.application.name 정보를 기반으로 forwarding 대상 micro-service routing 정보 설정

---
![image](https://user-images.githubusercontent.com/14158670/148354790-e95f016e-3850-4332-8d93-f5462d92e249.png)
