### ISSUE TITLE
[gateway]direct forwarding을 위한 RewritePath Filter routes 속성 적용

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#40]
spring.cloud.gateway.default-filters.routes.filters 항목의 RewritePath={path}/(?<segment>.*), /$\{segment} 옵션 설정을 통한
micro-service를 지칭하기 위해 명시했던 불필요한 URI 경로 제거 

- RewritePath=/user-service/(?<segment>.*), /$\{segment}
  - /user-service/**의 모든 요청에 대하여 /user-service경로를 제외하고 /** 경로로 포워딩 할 수 있도록 설정

```yml
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: e-commerce service gateway global filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
```

---
### 로그인 요청에 대한 gateway 설정 추가
filters: RemoveRequestHeader=Cookie
 - Post로 전달되는 요청을 매번 새로운 요청으로 인식 하기 위한 설정 추가

```yaml
spring:
  cloud:
    gateway:
      default-filters:
      routes:
        - id: {service-id}
          uri: lb://{registered service name to eureka server}
          predicates:
            - Path=/{endpoint user request path prefix}/**
          filters:
            - RewritePath=/{rewrite request path}/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
```
