### ISSUE TITLE
[micro-service]configurations service 연동

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#50]
### 필요 의존성
```groovy
dependencies {
  implementation 'org.springframework.cloud:spring-cloud-starter-config'
  implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
}
```
```yaml
spring.cloud.bootstrap.enabled=true
```

---

> bootstrap.yml :  configurations service로 부터 각 micro-service의 application.yml 보다 먼저 로딩 하기 위한 설정 정보
```yaml
spring:
  cloud:
    config:
      uri: { configurations service uri }
      name: { configurations file name } 
  profiles:
    active: { configurations profiles }
```

---
###
> bootstrap.yml의 configuration service정보로 기동된 micro service의 log
```log
: Fetching config from server at : { configurations service url }
: Located environment: name={configuration file name}, profiles=[{profiles info}], label=null, version={version info}
: Located property source: [BootstrapPropertySource {name='bootstrapProperties-configClient'}]
: No active profile set, falling back to default profiles: {profiles info}
``` 

---
변경된 Conrfiguration content에 대한 micro service 반영

- configuration 정보는 언제든지 변경 가능해야한다.
- 변경된 configuration service 정보를 micro-service에 적용하기 위해 서는 다음과 같은 선택지가 있다.
1. 빌드 -> 배포 과정없이 bootstrap.yml 리프레쉬를 위한 서버 재기동
2. Actuator refresh
3. Spring Cloud Bus

> spring boot actuator
- Application 상태, 모니터링
- Metric 수집을 위한 Http endpoint 제공

actuator가 적용된 application에서 actuator로 부터 조회 가능한 endpoint를 개방하는 옵션
```yml
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
```

---

###
> micro service의 profiles별 configuration을 호출하는 방법
ex)application.yml (prd)
ex)application-dev.yml
ex)application-stg.yml

로딩하고자 하는 profiles 를 bootstrap.yml의 spring.cloud.profiles.active에 명시
---

### 적용 단계
[ ] Step01 : External Configuration Repository 생성(file, git, etc)
[ ] Step02 : Spring Config Server Project 생성 및 설정
[ ] Step03 : Micro service의 Configuration을 External Configuration Repository로 이동
[ ] Step04 : Micro service에 bootstrap 관련 의존성 및 설정 추가
[ ] Test : Spring Config Server를 통한 Configuration 주입 여부 확인

---
### TODO
[ ] profiles 별 configuration 주입 여부 확인
[ ] 공개키 방식으로 암호화된 configuration 주입 시  복호화 여부 확인
[ ] configuration 변경 시 Spring Cloud Bus에 연결된 각 micro service의 변경 사항 전파 여부 확인

---
### Configuration 분리 기준
 - 변경이 지양되야 하는 설정 -> application.yml에 기술
 - 변경에 유연해야 하는 설정 -> Configurations Server에 이관
