### ISSUE TITLE
[micro-service]configurations 변경 전파 및 수신을 위한 Spring Cloud Bus 설정

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#51]
### Spring Cloud Bus
configuration service의 변경사항 발생 시, Spring Cloud Bus가 각 micro service에 변경 사항을 전파

- 분산 시스템의 노드(micro-service)를 경량 메세지 브로커(RabbitMQ or Kafka)와 연결
- 상태 및 구성에 대한 변경 사항을 연결된 노드에게 전달(broadcast)

---

### AMQP(Advanced Message Queuing Protocol), 메세지 지향 미들웨어를 위한 개방형 표준 응용 계층 프로토콜
- 메세지 지향, 큐잉, 라우팅(P2P, Publisher-subscriber), 신뢰성, 보안
- Erlang, RabbitMQ에서 사용

### Kafka Project
- Apache Software Foundation이 Scalar 언어로 개발한 오픈 소스 메세지 브로커 프로젝트
- 분산형 스트리밍 플랫폼
- 대용량 데이터 처리 가능한 메시징 시스템

### RabbitMQ vs Kafka
> RabbitMQ : 적은 데이터를 안정적으로 전달하는 것을 보장해야 할 때 고려

- 메세지 브로커
- 초당 20+@ 메세지를 소비자에게 전달
- 메세지 전달 보장, 시스템 간 메세지 전달
- 브로커, 소비자 중심

> Kafka : 대용량의 데이터를 빠르게 처리 할 때 고려

- 초당 100k+@ 이상의 이벤트 처리
- Pub/Sub, Topic에 메세지 전달
- Ack를 기다리지 않고 전달 가능
- 생산자 중심

---
### Spring Cloud Bus를 이용한 changed configuration refresh

갱신 : POST /busrefresh
대상 : Spring Cloud Bus에 연결된 어떤 노드라도 갱신 요청 수신 시, Spring Cloud Bus에 변경 사항을 전달하고, Spring Cloud Bus은 연결된 다른 노드에게 변경 사항을 전파

---
### RabbitMQ docker-compose.yml
```yaml
version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq-stream
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
```

### 필요 의존성
> configuration server & gateway & micro services

```groovy
dependencies {
  implementation 'org.springframework.cloud:spring-cloud-starter-config'
  implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
  implementation 'org.springframework.cloud:spring-cloud-starter-bus-amqp'
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
}
```

> application.yml : Spring Cloud Bus에 등록되는 Application에 아래 설정을 추가
```yaml
spring:
  rabbitmq: 127.0.0.1
  port: 5672
  usernmae: admin
  password: admin

---
management:
  endpoints:
    web:
      exposure:
        include: busrefresh
```

### Local Test
1. RabbitMQ server 기동
2. Spring cloud config server 기동
3. Eureka server 기동
4. Gateway server 기동
5. Each micro service x3 기동
6. private Git Repository configuration 변경
7. POST /actuator/busrefresh 호출
8. Spring cloud bus에 연결된 application에 configuration 전파 확인
