### ISSUE TITLE
Micro service의 분산 추적을 위한 Spring Cloud Sleuth and Zipzin

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#61]
마이크로 서비스간에 연결되어 있는 상태, 통신 시간 및 정상 여부, 호출 관계 및 흐름, 
### Zipzin
- Micro service간의 통신 흐름을 파악

### Reference URL
- Twitter에서 사용하는 분산 환경의 Timing 데이터 수집, 추적 시스템 (오픈소스)
- Google Drapper에서 발전하였으며, 분산환경에서의 시스템 병목 현상 파악
- Collector Query Service, Databasem WebUI로 구성
- Span
  - 하나의 요청에 사용되는 작업의 단위
  - 64 bit unique ID
- Trace
   - 트리 구조로 이뤄진 Span set
   - 하나의 요청에 대한 같은 Trace ID 발급

### Spring Cloud Sleuth
- Spring Boot Application을 Zipkin 과 연동
- 요청 값에 따른 Trace ID, Span ID 부여
- Sleuth는 로그 수집을 Zipkin은 로그 시각화를 담당
- Trace ID와 Span ID를 로그에 추가 가능
  - servlet filter
  - rest template
  - scheduled actions
  - message channels
  - feign client

---
### 필요 의존성
```groovy
dependencies {
  implementation("org.springframework.cloud:spring-cloud-starter-sleuth")
  implementation 'org.springframework.cloud:spring-cloud-sleuth-zipkin'
  implementation 'org.springframework.cloud:spring-cloud-starter-sleuth'
}

```

---
### Docker compose
```yaml
# https://github.com/openzipkin-attic/docker-zipkin/blob/master/docker-compose.yml
version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
``` 
> application.yml
```yaml
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth
    sampler:
      probability: 1.0 (발생되는 로그의 설정 빈도수 만큼 Zipkin에 전달 maxium: 1.0(100%))
```

### Reference URL
- [zipkin official](https://zipkin.io/)
- [spring cloud sleuth offical](https://spring.io/projects/spring-cloud-sleuth)
